### ISSUE TITLE
Location in the network

### ISSUE THREAD

**Issue by xiaochenwise** [poppinace/sapa#2]
Hello, thank you for your work, I want to try to put your upsample into my neural network, which module should I call? Do you place the module directly after the feature map?

**Comment by poppuppy** [comment]
Hello. After installing sapa, you can upsample the feature following L61-L64 in SAPA.py.

**Comment by xiaochenwise** [comment]
Hello, I used the resnet50 model. The input is 256x256 image, the output feature map size of layer3 is 16x16, and the output feature map size of layer4 is 8x8. These two feature maps are used as input of SAPA module to complete the upsampling. Am I doing the right thing?

**Comment by poppuppy** [comment]
Yeah. And you can gradually upsample the 8x8 feature to 256x256 with the help of features in different layers in the backbone as the guidance.
